export const FETCH_BASKET_REQUEST = 'FETCH_BASKET_REQUEST';
export const FETCH_BASKET_SUCCESS = 'FETCH_BASKET_SUCCESS';
export const FETCH_BASKET_FAILURE = 'FETCH_BASKET_FAILURE';
export const BASKET_ADD_ITEM = 'BASKET_ADD_ITEM';
export const BASKET_REMOVE_ITEM = 'BASKET_REMOVE_ITEM';
export const FLUSH_BASKET = 'FLUSH_BASKET';
