export const FETCH_NOTEBOOKS_REQUEST = 'FETCH_NOTEBOOKS_REQUEST';
export const FETCH_NOTEBOOKS_SUCCESS = 'FETCH_NOTEBOOKS_SUCCESS';
export const FETCH_NOTEBOOK_SUCCESS = 'FETCH_NOTEBOOK_SUCCESS';
export const FETCH_NOTEBOOKS_FAILURE = 'FETCH_NOTEBOOKS_FAILURE';
export const FETCH_NOTEBOOKS_SEARCH = 'FETCH_NOTEBOOKS_SEARCH';
export const FETCH_NOTEBOOK_GET = 'FETCH_NOTEBOOK_GET';
