export const ORDER_USER_REQUEST = 'ORDER_USER_REQUEST';
export const ORDER_USER_SUCCESS = 'ORDER_USER_SUCCESS';
export const ORDER_USER_FAILURE = 'ORDER_USER_FAILURE';
export const ORDER_PRODUCTS_REQUEST = 'ORDER_PRODUCTS_REQUEST';
export const ORDER_PRODUCTS_SUCCESS = 'ORDER_PRODUCTS_SUCCESS';
export const ORDER_PRODUCTS_FAILURE = 'ORDER_PRODUCTS_FAILURE';
export const SET_ORDER_INIT_STEP = 'SET_ORDER_INIT_STEP';
export const SET_ORDER_USER_STEP = 'SET_ORDER_USER_STEP';
