export const FETCH_TVS_REQUEST = 'FETCH_TVS_REQUEST';
export const FETCH_TVS_SUCCESS = 'FETCH_TVS_SUCCESS';
export const FETCH_TV_SUCCESS = 'FETCH_TV_SUCCESS';
export const FETCH_TVS_FAILURE = 'FETCH_TVS_FAILURE';
export const FETCH_TVS_SEARCH = 'FETCH_TVS_SEARCH';
export const FETCH_TV_GET = 'FETCH_TV_GET';
